"""Stable privacy limits and archive-format constants."""

EXPORT_FORMAT_VERSION = 5
SUPPORTED_IMPORT_FORMAT_VERSIONS = (1, 2, 3, 4, 5)
IMPORT_MAX_RECORDS = 10_000
IMPORT_MAX_PAYLOAD_BYTES = 5 * 1024 * 1024
IMPORT_MAX_TEXT_LENGTH = 2_048
IMPORT_MAX_DURATION_SEC = 7 * 24 * 60 * 60
RETENTION_PERMANENT = None
RETENTION_MIN_DAYS = 1
RETENTION_MAX_DAYS = 360
META_RETENTION_DAYS = "retention_days"
META_RETENTION_PERMANENT = "permanent"
